/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package proyectofinal;

import javax.swing.JOptionPane;

/**
 *
 * @author MarDav
 */
public class juego extends javax.swing.JFrame {
int vidas=3, ale;
    /** Creates new form juego */
    public juego() {
        initComponents();
        ale=(int)(Math.random()*63+1);
        nu.setText(String.valueOf(ale));
        Vid.setText(String.valueOf(vidas));
        otra.setVisible(false);
        gan.setVisible(false);
        pie1.setVisible(false);
        pie2.setVisible(false);
        pie3.setVisible(false);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        nu = new javax.swing.JLabel();
        txt1 = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jugar = new javax.swing.JButton();
        Vid = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jj = new javax.swing.JLabel();
        otra = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        pie1 = new javax.swing.JLabel();
        pie2 = new javax.swing.JLabel();
        pie3 = new javax.swing.JLabel();
        gan = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("Adivina el Binario");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(137, 16, -1, -1));

        nu.setText("Numero");
        getContentPane().add(nu, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 170, -1, -1));
        getContentPane().add(txt1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 170, 172, -1));

        jLabel2.setText("=");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 170, -1, -1));

        jugar.setText("Jugar");
        jugar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jugarActionPerformed(evt);
            }
        });
        getContentPane().add(jugar, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 250, 90, -1));

        Vid.setText("V");
        getContentPane().add(Vid, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 200, -1, -1));

        jLabel4.setText("Vidas =");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 200, -1, -1));

        jButton2.setText("Regresar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        jj.setText("jLabel5");
        getContentPane().add(jj, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 140, 128, -1));

        otra.setText("Volver a jugar");
        otra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                otraActionPerformed(evt);
            }
        });
        getContentPane().add(otra, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 250, -1, -1));

        jButton1.setText("Estudia");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 40, 90, -1));

        jLabel3.setText("Nota:");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 80, -1, -1));

        jLabel5.setText("Omite los ceros a la derecha hasta el 1");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 80, -1, -1));

        jLabel6.setText("Ejemplo:");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 110, -1, -1));

        jLabel7.setText("000101");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 110, -1, -1));

        jLabel8.setText("Incorrecto:");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 110, -1, -1));

        jLabel9.setText("Correcto:");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 130, -1, -1));

        jLabel10.setText("101");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 130, -1, -1));

        pie1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/proyectofinal/imagenes/pie1.jpg"))); // NOI18N
        getContentPane().add(pie1, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 190, -1, -1));

        pie2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/proyectofinal/imagenes/pie2.jpg"))); // NOI18N
        getContentPane().add(pie2, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 190, -1, -1));

        pie3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/proyectofinal/imagenes/pie3.jpg"))); // NOI18N
        getContentPane().add(pie3, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 190, 150, -1));

        gan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/proyectofinal/imagenes/gana.jpg"))); // NOI18N
        getContentPane().add(gan, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 190, 170, 110));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jugarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jugarActionPerformed
       String bi=Integer.toBinaryString(ale);
       jj.setText(bi);
       
       String dato;
       dato=txt1.getText();
       
       if(dato.equals(bi)){
           pie1.setVisible(false);
           pie2.setVisible(false);
           pie3.setVisible(false);
           gan.setVisible(true);
           JOptionPane.showMessageDialog(null,"Felicidades Ganaste");
           jugar.setVisible(false);
           otra.setVisible(true);
           
       }
        
       else if(vidas==3){
           vidas--;
           Vid.setText(String.valueOf(vidas));
           pie3.setVisible(true);
       }
       else if(vidas==2){
           vidas--;
           Vid.setText(String.valueOf(vidas));
           pie3.setVisible(false);
           pie2.setVisible(true);
       }
       else if(vidas==1){
           vidas--;
           Vid.setText(String.valueOf(vidas));
           pie1.setVisible(true);
           pie2.setVisible(false);
           JOptionPane.showMessageDialog(null,"Perdiste");
           jugar.setVisible(false);
           otra.setVisible(true);
           vidas=3;
           Vid.setText(String.valueOf(vidas));
       }
       
       
       
       
    }//GEN-LAST:event_jugarActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
       Inicio obj = new Inicio();
       obj.setVisible(true);
       this.dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void otraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_otraActionPerformed
        ale=(int)(Math.random()*63+1);
        nu.setText(String.valueOf(ale));
        jugar.setVisible(true);
        otra.setVisible(false);
        gan.setVisible(false);
        pie1.setVisible(false);
    }//GEN-LAST:event_otraActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        estudia obj = new estudia();
        obj.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(juego.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(juego.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(juego.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(juego.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new juego().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Vid;
    private javax.swing.JLabel gan;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel jj;
    private javax.swing.JButton jugar;
    private javax.swing.JLabel nu;
    private javax.swing.JButton otra;
    private javax.swing.JLabel pie1;
    private javax.swing.JLabel pie2;
    private javax.swing.JLabel pie3;
    private javax.swing.JTextField txt1;
    // End of variables declaration//GEN-END:variables

}
